# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-09 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [

        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name_slack', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slack_token', models.CharField(max_length=100)),
                ('access_token_fb', models.TextField(default='')),
                ('team_domain', models.CharField(max_length=50)),
                ('team_id', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
                ('user_name_czm', models.CharField(max_length=100)),
                ('state_params', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2018, 5, 9, 23, 9, 56, 731203)),
        ),
    ]
