# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('platform', models.CharField(max_length=50)),
                ('osver', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('company_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('steps', models.TextField()),
                ('result_expected', models.TextField()),
                ('actual_excepted', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('appid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdoc.AppInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=100)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdoc.Company')),
            ],
        ),
        migrations.AddField(
            model_name='appinfo',
            name='companyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdoc.Company'),
        ),
    ]
